# docker-compose.prod.yml - for production deployment
version: "3.8"
services:
  mongo:
    image: mongo:7
    container_name: app-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: app-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DENO_ENV=production
      - MONGO_URI=mongodb://root:example@mongo:27017/
    volumes:
      - uploads:/app/uploads
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: app-frontend
    restart: unless-stopped
    ports:
      - "3000:4173"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongo_data:
  uploads:

networks:
  app-network:
    driver: bridge
